# サーバーポート設定（デフォルト: 8080）
# server.port=8080

# YOLP appid を設定してください
yolp.appid=dmVyPTIwMjUwNyZpZD1YbnZnbXFtcXc3Jmhhc2g9T1dOaFpqQTJOREUwTWpOaE5EQTVOQQ

spring.devtools.remote.restart.enabled=true
spring.devtools.livereload.enabled=true